dataset_name: multioped
summarizer_name: bart_e2e
tokenizer:
  name: google/flan-t5-large
model:
  name: google/flan-t5-large
rescoring:
  type: latent_reconstruction
  preprocessed_dataset_path: /home/mila/c/cesare.spinoso/RSASumm/data/multioped/test.csv
  generated_summaries_yaml: /home/mila/c/cesare.spinoso/RSASumm/src/generate_summaries/generated_summaries/e2e_summaries.yaml
  rescored_summaries_jsonl_path: /home/mila/c/cesare.spinoso/RSASumm/data/rescoring/latent_reconstruction/bart_e2e/2024-03-29-15:25:07.957846.jsonl
  batch_size: 32
output_directory: /network/scratch/c/cesare.spinoso/rsasumm/rescoring
write_config_directory: /home/mila/c/cesare.spinoso/RSASumm/src/rescoring/config_instances/latent_reconstruction/bart_e2e
finished_running: false
