dataset_name: debatepedia
summarizer_name: t5_generic
tokenizer:
  name: google/flan-t5-large
model:
  name: google/flan-t5-large
rescoring:
  type: latent_reconstruction
  preprocessed_dataset_path: /home/mila/c/cesare.spinoso/RSASumm/data/debatepedia/preprocessed.csv
  generated_summaries_yaml: /home/mila/c/cesare.spinoso/RSASumm/src/generate_summaries/generated_summaries/generic_summaries.yaml
  batch_size: 64
output_directory: /network/scratch/c/cesare.spinoso/rsasumm/rescoring
write_config_directory: /home/mila/c/cesare.spinoso/RSASumm/src/rescoring/config_instances/latent_reconstruction/t5_generic