dataset:
  name: covidet
  path: /home/mila/c/cesare.spinoso/RSASumm/data/covidet/preprocessed.csv
  source_name: document
  reference_name: summary
  document_id_name: document_id
tokenizer:
  name: allenai/led-large-16384-arxiv
model:
  name: allenai/led-large-16384-arxiv
generation:
  batch_size: 16
  summary_type: generic
  generated_jsonl_paths:
  - /home/mila/c/cesare.spinoso/RSASumm/data/generate_summaries/led_generic/2024-03-16-02:19:11.883909.jsonl
  seed: 42
  generate_kwargs:
    num_beams: 5
    num_beam_groups: 5
    num_return_sequences: 5
    diversity_penalty: 1.0
    max_new_tokens: 150
    early_stopping: true
    output_scores: true
    return_dict_in_generate: true
output_directory: /network/scratch/c/cesare.spinoso/rsasumm/generate_summaries/led_generic
write_config_directory: /home/mila/c/cesare.spinoso/RSASumm/src/generate_summaries/config_instances/led_generic
finished_running: true
