dataset:
  name: multioped
  path: /home/mila/c/cesare.spinoso/RSASumm/data/multioped/test.csv
  source_name: document
  question_name: question
  reference_name: summary
  document_id_name: document_id
tokenizer:
  name: meta-llama/Meta-Llama-3-8B-Instruct
  maximum_length: 4096
model:
  name: meta-llama/Meta-Llama-3-8B-Instruct
prompt_template: '<|start_header_id|>system<|end_header_id|>You are a helpful, respectful
  and honest assistant specializing in query-focused summarization.<|eot_id|><|start_header_id|>user<|end_header_id|>
  Read the following document and related question. Provide a summary which both summarizes
  the document as well as answers the question. That is, the summary should summarize
  the main points of the document while providing an answer to the given question.
  Do not generate anything else other than the summary. Question: {q} Document: {s}
  Summary:<|eot_id|><|start_header_id|>assistant<|end_header_id|>'
generation:
  batch_size: 2
  summary_type: e2e
  generated_jsonl_paths:
  - /home/mila/c/cesare.spinoso/RSASumm/data/generate_summaries/llama3_e2e/multioped/2024-07-17-16:08:05.578829.jsonl
  seed: 42
  generate_kwargs:
    num_beams: 5
    num_beam_groups: 5
    num_return_sequences: 5
    diversity_penalty: 1.0
    do_sample: false
    max_new_tokens: 300
    temperature: null
    top_p: null
    early_stopping: true
    output_scores: true
    return_dict_in_generate: true
output_directory: /network/scratch/c/cesare.spinoso/rsasumm/generate_summaries/llama3_e2e/multioped
write_config_directory: /home/mila/c/cesare.spinoso/RSASumm/src/generate_summaries/config_instances/llama3_e2e
finished_running: true
