dataset:
  name: "multioped"
  path: /home/mila/c/cesare.spinoso/RSASumm/data/multioped/preprocessed.csv
  split: "all"
  source_name: "document"
  reference_name: "summary"
tokenizer:
  name: t5-small
model:
  name: t5-small
generation:
  batch_size: 16
  seed: 42
  generate_kwargs:
    num_beams: 5
    # num_beam_groups is the number of groups to divide num_beams into in order to ensure diversity among the beams
    # still need to specify the number of sequences to output
    num_beam_groups: 5
    num_return_sequences: 5
    diversity_penalty: 1.0
    max_length: 150
    early_stopping: True
    output_scores: True
    return_dict_in_generate: True
output_directory: /network/scratch/c/cesare.spinoso/rsasumm/generate_summaries
write_config_directory: /home/mila/c/cesare.spinoso/RSASumm/src/generate_summaries/testing
