dataset:
  name: multioped
  generated_qs_path: /home/mila/c/cesare.spinoso/RSASumm/data/generate_questions/2024-07-18-11:32:41.810674.jsonl
tokenizer:
  name: meta-llama/Meta-Llama-3-8B-Instruct
  model_max_length: 4096
model:
  name: meta-llama/Meta-Llama-3-8B-Instruct
qa:
  prompt: "<|start_header_id|>system<|end_header_id|>You are a helpful, respectful and honest assistant specializing in question answering.<|eot_id|><|start_header_id|>user<|end_header_id|> Read the following document and then answer the question about it. Your answer should be clear, concise and accurate. Do not provide anything else other than the answer to the question. Document: {d} Question: {q} Answer: <|eot_id|><|start_header_id|>assistant<|end_header_id|>"
  batch_size: 2
  generate_kwargs:
    num_beams: 5
    num_return_sequences: 1
    max_new_tokens: 100
    early_stopping: True
    return_dict_in_generate: True
  generated_jsonl_path: /home/mila/c/cesare.spinoso/RSASumm/data/qa_generation_for_generated_qs/2024-08-08-13:01:51.598134.jsonl
output_directory: /network/scratch/c/cesare.spinoso/rsasumm/qa_generation_for_generated_qs
write_config_directory: /home/mila/c/cesare.spinoso/RSASumm/src/rescoring/config_instances/qa_generation_for_generated_qs