defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  
hydra:  
# Disable output directory
  output_subdir: null  
  run:  
    dir: .
# Enable sweeping
  sweeper:
    params:
      hps.learning_rate: 3e-4,3e-5
      hps.gradient_accumulation_steps: 1,2,4

# Config settings
model:
  name: facebook/bart-large
  is_logging_rouge_scores: true
  test_interval_computation: 5  
  test_num_batch_sample: 1
  generation_kwargs:
    do_sample: True
    max_new_tokens: 100
data:
  name: multioped
  csv_dir: /home/mila/c/cesare.spinoso/RSASumm/data/multioped
  dataset_formatting:
    data_format: e2e
hps:
  train_batch_size: 16
  test_batch_size: 16
  gradient_accumulation_steps: 1
  epochs: 50
  patience: 30
  learning_rate: 3e-4
  weight_decay: 0.1
  warmup: 0.1
output_directory: /network/scratch/c/cesare.spinoso/rsasumm/finetuning
write_config_directory: /home/mila/c/cesare.spinoso/RSASumm/src/finetuning/literal_summarizer/config_instances/bart
commit: false
