datasets:
  covidet: /home/mila/c/cesare.spinoso/RSASumm/data/covidet/test.csv
  debatepedia: /home/mila/c/cesare.spinoso/RSASumm/data/debatepedia/test.csv
  duc_single: /home/mila/c/cesare.spinoso/RSASumm/data/duc/duc_single/preprocessed.csv
  multioped: /home/mila/c/cesare.spinoso/RSASumm/data/multioped/test.csv
  qmsum: /home/mila/c/cesare.spinoso/RSASumm/data/qmsum/test.csv
merged_rescores:
  llama2_generic: /home/mila/c/cesare.spinoso/RSASumm/data/rescoring/merge_rescores/2024-04-03-16:18:15.135836
  # bart_generic: /home/mila/c/cesare.spinoso/RSASumm/data/rescoring/merge_rescores/2024-03-24-18:33:34.200968
  # led_generic: /home/mila/c/cesare.spinoso/RSASumm/data/rescoring/merge_rescores/2024-03-24-18:33:54.665062
  # peg_generic: /home/mila/c/cesare.spinoso/RSASumm/data/rescoring/merge_rescores/2024-03-24-18:34:17.256365
  # t5_generic: /home/mila/c/cesare.spinoso/RSASumm/data/rescoring/merge_rescores/2024-03-24-18:34:59.103927
  # For a sanity check, below filtering is 0
  # bart_e2e: /home/mila/c/cesare.spinoso/RSASumm/data/rescoring/merge_rescores/2024-04-02-09:56:23.085745
  # led_e2e: /home/mila/c/cesare.spinoso/RSASumm/data/rescoring/merge_rescores/2024-04-02-10:27:56.615451
  # llama2_e2e: /home/mila/c/cesare.spinoso/RSASumm/data/rescoring/merge_rescores/2024-04-02-10:28:32.547098
write_config_directory: /home/mila/c/cesare.spinoso/RSASumm/src/rescoring/config_instances/filter
output_directory: /network/scratch/c/cesare.spinoso/rsasumm/rescoring/merge_rescores