dataset_name: duc_single
tokenizer:
  name: meta-llama/Llama-2-7b-chat-hf
  model_max_length: 4096
model:
  name: meta-llama/Llama-2-7b-chat-hf
qa:
  preprocessed_dataset_path: /home/mila/c/cesare.spinoso/RSASumm/data/duc/duc_single/preprocessed.csv
  batch_size: 1
  incontext-question: What does John Daniel Davidson believe about the current effort
    to remove monuments from America's history?
  incontext-content: The current effort to remove monuments from America's history
    has become too extreme, believes John Daniel Davidson of The Federalist. This
    movement has gone beyond just removing statues of racist historical figures, it
    has become an ideological purity test. When statues of Christopher Columbus are
    torn down and the Tomb of the Unknown Soldier is defaced, something has gone too
    far. These protesters are attacking US history. They see America as something
    that needs to be torn down. Columbus helped establish this country, which has
    embodied democracy and freedom. Denying this is political extremism of the worst
    kind.
  incontext-answer: Removing the statues is sheer fanaticism and an attack on US history
    and values.
  generate_kwargs:
    num_beams: 5
    num_return_sequences: 1
    max_new_tokens: 50
    early_stopping: true
output_directory: /network/scratch/c/cesare.spinoso/rsasumm/qa_generation
write_config_directory: /home/mila/c/cesare.spinoso/RSASumm/src/rescoring/config_instances/qa_generation
commit: false
finished_running: false
