dataset_name: multioped
tokenizer:
  name: meta-llama/Llama-2-7b-chat-hf
  model_max_length: 4096
model:
  name: meta-llama/Llama-2-7b-chat-hf
qa:
  preprocessed_dataset_path: /home/mila/c/cesare.spinoso/RSASumm/data/multioped/test.csv
  batch_size: 1
  generate_kwargs:
    num_beams: 5
    num_return_sequences: 1
    max_new_tokens: 50
    early_stopping: true
    return_dict_in_generate: true
output_directory: /network/scratch/c/cesare.spinoso/rsasumm/qa_generation
write_config_directory: /home/mila/c/cesare.spinoso/RSASumm/src/rescoring/config_instances/qa_generation
finished_running: false
