rescored_dataset_path: /home/mila/c/cesare.spinoso/RSASumm/data/rescoring/2024-02-10-12:43:37.896952.jsonl
write_config_directory: /home/mila/c/cesare.spinoso/RSASumm/src/rerank/config_instances
output_results_directory: /home/mila/c/cesare.spinoso/RSASumm/src/rerank/results
evaluation:
  reranked_scores:
    score_type:
      - rouge1
      - rouge2
      - rougeL
    num_seq_per_source: 5
    ranking_types:
      random: True
      max: True
      direct_score: pred_score
      rsa_score: loss_source_given_pred
  reranked_frequencies:
    score_type:
    - rouge1
    - rouge2
    - rougeL
    num_seq_per_source: 5
    ranking_types:
      random: True
      max: True
      direct_score: pred_score
      rsa_score: loss_source_given_pred