model:
  name: facebook/bart-large-cnn
  is_logging_rouge_scores: true
  test_interval_computation: 5
  test_num_batch_sample: 1
  generation_kwargs:
    num_beams: 5
    max_new_tokens: 150
    early_stopping: true
data:
  name: multioped
  csv_dir: /home/mila/c/cesare.spinoso/RSASumm/data/multioped
  dataset_formatting:
    data_format: e2e
hps:
  train_batch_size: 16
  test_batch_size: 16
  gradient_accumulation_steps: 1
  epochs: 25
  patience: 5
  learning_rate: 3.0e-05
  weight_decay: 0.1
  warmup: 0.1
output_directory: /network/scratch/c/cesare.spinoso/rsasumm/finetuning
write_config_directory: /home/mila/c/cesare.spinoso/RSASumm/src/finetuning/config_instances/bart
commit: false
finished_running: true
best_model_path: /network/scratch/c/cesare.spinoso/rsasumm/finetuning/2024-04-24-17:41:40.907978/lightning_logs/version_0/checkpoints/epoch=21-step=2486.ckpt
