model:
  name: facebook/bart-large
  is_logging_rouge_scores: true
  test_interval_computation: 5
  test_num_batch_sample: 1
  generation_kwargs:
    num_beams: 5
    max_new_tokens: 150
    early_stopping: true
data:
  name: covidet
  csv_dir: /home/mila/c/cesare.spinoso/RSASumm/data/covidet
  dataset_formatting:
    data_format: e2e
    info_req_formatter: Describe the {} of this post.
hps:
  train_batch_size: 16
  test_batch_size: 16
  gradient_accumulation_steps: 1
  epochs: 30
  patience: 5
  learning_rate: 3.0e-05
  weight_decay: 0.1
  warmup: 0.1
output_directory: /network/scratch/c/cesare.spinoso/rsasumm/finetuning
write_config_directory: /home/mila/c/cesare.spinoso/RSASumm/src/finetuning/literal_summarizer/config_instances/bart
commit: false
finished_running: true
best_model_path: /network/scratch/c/cesare.spinoso/rsasumm/finetuning/2024-05-01-14:46:36.991512/lightning_logs/version_0/checkpoints/epoch=25-step=6812.ckpt
