defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  
hydra:  
# Disable output directory
  output_subdir: null  
  run:  
    dir: .
# Config settings
model:
  name: allenai/led-large-16384
  is_logging_rouge_scores: false
lora:
  r: 32
  lora_alpha: 32
  target_modules:
    - "query"
    - "values"
  lora_dropout: 0.1
  bias: "lora_only"
data:
  name: debatepedia
  csv_dir: /home/mila/c/cesare.spinoso/RSASumm/data/debatepedia
  dataset_formatting:
    data_format: e2e
hps:
  train_batch_size: 8
  test_batch_size: 8
  gradient_accumulation_steps: 2
  epochs: 30
  patience: 5
  learning_rate: 3e-5
  weight_decay: 0.1
  warmup: 0.1
output_directory: /network/scratch/c/cesare.spinoso/rsasumm/finetuning
write_config_directory: /home/mila/c/cesare.spinoso/RSASumm/src/finetuning/literal_summarizer/config_instances/led
commit: false
