model:
  name: allenai/led-large-16384
  is_logging_rouge_scores: false
data:
  name: multioped
  csv_dir: /home/mila/c/cesare.spinoso/RSASumm/data/multioped
  dataset_formatting:
    data_format: e2e
hps:
  train_batch_size: 4
  test_batch_size: 4
  gradient_accumulation_steps: 4
  epochs: 30
  patience: 5
  learning_rate: 3.0e-05
  weight_decay: 0.1
  warmup: 0.1
output_directory: /network/scratch/c/cesare.spinoso/rsasumm/finetuning
write_config_directory: /home/mila/c/cesare.spinoso/RSASumm/src/finetuning/literal_summarizer/config_instances/led
commit: false
finished_running: false
