model:
  name: allenai/led-large-16384
  is_logging_rouge_scores: true
  test_interval_computation: 5
  test_num_batch_sample: 1
  generation_kwargs:
    num_beams: 5
    max_new_tokens: 150
    early_stopping: true
data:
  name: debatepedia
  csv_dir: /home/mila/c/cesare.spinoso/RSASumm/data/debatepedia
  dataset_formatting:
    data_format: e2e
hps:
  train_batch_size: 8
  test_batch_size: 8
  gradient_accumulation_steps: 2
  epochs: 30
  patience: 5
  learning_rate: 3.0e-05
  weight_decay: 0.1
  warmup: 0.1
output_directory: /network/scratch/c/cesare.spinoso/rsasumm/finetuning
write_config_directory: /home/mila/c/cesare.spinoso/RSASumm/src/finetuning/literal_summarizer/config_instances/led
commit: false
finished_running: true
best_model_path: ''
