model:
  name: allenai/led-large-16384
  is_logging_rouge_scores: false
lora:
  r: 32
  lora_alpha: 32
  target_modules:
  - query
  - values
  lora_dropout: 0.1
  bias: lora_only
data:
  name: multioped
  csv_dir: /home/mila/c/cesare.spinoso/RSASumm/data/multioped
  dataset_formatting:
    data_format: e2e
hps:
  train_batch_size: 2
  test_batch_size: 2
  gradient_accumulation_steps: 8
  epochs: 30
  patience: 5
  learning_rate: 3.0e-05
  weight_decay: 0.1
  warmup: 0.1
output_directory: /network/scratch/c/cesare.spinoso/rsasumm/finetuning
write_config_directory: /home/mila/c/cesare.spinoso/RSASumm/src/finetuning/literal_summarizer/config_instances/led
commit: false
finished_running: false
