dataset:
  name: covidet
  path: /home/mila/c/cesare.spinoso/RSASumm/data/covidet/preprocessed.csv
  source_name: document
  reference_name: summary
  document_id_name: document_id
tokenizer:
  name: facebook/bart-large-cnn
model:
  name: facebook/bart-large-cnn
generation:
  batch_size: 16
  summary_type: generic
  seed: 42
  generate_kwargs:
    num_beams: 5
    num_beam_groups: 5
    num_return_sequences: 5
    diversity_penalty: 1.0
    max_new_tokens: 150
    early_stopping: True
    output_scores: True
    return_dict_in_generate: True
output_directory: /network/scratch/c/cesare.spinoso/rsasumm/generate_summaries/bart_generic
write_config_directory: /home/mila/c/cesare.spinoso/RSASumm/src/generate_summaries/config_instances/bart_generic

