dataset:
  name: qmsum
  path: /home/mila/c/cesare.spinoso/RSASumm/data/qmsum/test_new.csv
  source_name: document
  question_name: question
  reference_name: summary
  document_id_name: document_id
tokenizer:
  name: meta-llama/Meta-Llama-3-8B-Instruct
  maximum_length: 4096
model:
  name: meta-llama/Meta-Llama-3-8B-Instruct
prompt_template: '<|start_header_id|>system<|end_header_id|>You are a helpful, respectful
  and honest assistant specializing in query-focused summarization.<|eot_id|><|start_header_id|>user<|end_header_id|>
  Read the following document and related questions. Provide a summary which both
  summarizes the document as well as answers the questions. That is, the summary should
  summarize the main points of the document while providing answers to the given questions.
  Do not generate anything else other than the summary. Questions: {q} Document: {s}
  Summary:<|eot_id|><|start_header_id|>assistant<|end_header_id|>'
generation:
  batch_size: 1
  summary_type: e2e
  generate_kwargs:
    num_return_sequences: 10
    max_new_tokens: 300
    output_scores: true
    output_logits: true
    return_dict_in_generate: true
    do_sample: true
    temperature: 2.0
output_directory: /network/scratch/c/cesare.spinoso/rsasumm/generate_summaries/llama3_qfs/qmsum
write_config_directory: /home/mila/c/cesare.spinoso/RSASumm/src/generate_summaries/config_instances/llama3_qfs
finished_running: true
