tokenizer:
  name: t5-small
model:
  name: t5-small
rescoring:
  summary_jsonl_path: /home/mila/c/cesare.spinoso/RSASumm/data/generate_data/2024-02-09-21:31:46.230830.jsonl
  batch_size: 16
output_directory: /network/scratch/c/cesare.spinoso/rsasumm/rescoring
write_config_directory: /home/mila/c/cesare.spinoso/RSASumm/src/rescoring/config_instances
finished_running: true
