dataset:
  name: debatepedia
  path: /home/mila/c/cesare.spinoso/RSASumm/data/debatepedia/preprocessed.csv
  source_name: document
  reference_name: summary
  document_id_name: document_id
tokenizer:
  name: google/pegasus-large
model:
  name: google/pegasus-large
generation:
  batch_size: 16
  summary_type: generic
  generated_jsonl_paths:
  - /home/mila/c/cesare.spinoso/RSASumm/data/generate_summaries/peg_generic/2024-03-16-00:33:49.365996.jsonl
  seed: 42
  generate_kwargs:
    num_beams: 5
    num_beam_groups: 5
    num_return_sequences: 5
    diversity_penalty: 1.0
    max_new_tokens: 150
    early_stopping: true
    output_scores: true
    return_dict_in_generate: true
output_directory: /network/scratch/c/cesare.spinoso/rsasumm/generate_summaries/peg_generic
write_config_directory: /home/mila/c/cesare.spinoso/RSASumm/src/generate_summaries/config_instances/peg_generic
finished_running: false
