dataset:
  name: debatepedia
  path: /home/mila/c/cesare.spinoso/RSASumm/data/debatepedia/preprocessed.csv
  source_name: document
  reference_name: summary
  document_id_name: document_id
tokenizer:
  name: google/flan-t5-large
model:
  name: google/flan-t5-large
generation:
  batch_size: 16
  summary_type: generic
  generated_jsonl_paths:
    - /home/mila/c/cesare.spinoso/RSASumm/data/generate_summaries/t5_generic/2024-03-15-23:03:15.039264.jsonl
  seed: 42
  generate_kwargs:
    num_beams: 5
    num_beam_groups: 5
    num_return_sequences: 5
    diversity_penalty: 1.0
    max_new_tokens: 150
    early_stopping: True
    output_scores: True
    return_dict_in_generate: True
output_directory: /network/scratch/c/cesare.spinoso/rsasumm/generate_summaries/t5_generic
write_config_directory: /home/mila/c/cesare.spinoso/RSASumm/src/generate_summaries/config_instances/t5_generic
