dataset:
  name: multioped
  path: /home/mila/c/cesare.spinoso/RSASumm/data/multioped/test.csv
  source_name: document
  question_name: question
  reference_name: summary
  document_id_name: document_id
tokenizer:
  name: facebook/bart-large
model:
  name: facebook/bart-large
  path_to_checkpoint: /network/scratch/c/cesare.spinoso/rsasumm/finetuning/2024-08-06-17:38:51.477512/lightning_logs/version_0/checkpoints/epoch=43-step=4972.ckpt
generation:
  batch_size: 5
  summary_type: e2e
  generate_kwargs:
    num_return_sequences: 10
    num_beams: null
    max_new_tokens: 300
    output_scores: true
    output_logits: true
    return_dict_in_generate: true
    do_sample: true
    top_p: 0.95
    temperature: 1.2
output_directory: /network/scratch/c/cesare.spinoso/rsasumm/generate_summaries/bart_finetuned_qfs
write_config_directory: /home/mila/c/cesare.spinoso/RSASumm/src/generate_summaries/config_instances/bart_finetuned_qfs
commit: false
finished_running: true
