dataset:
  name: squality
  path: /home/mila/c/cesare.spinoso/RSASumm/data/qmsum/test.csv
  source_name: document
  question_name: question
  reference_name: summary
  document_id_name: document_id
tokenizer:
  name: facebook/bart-large
model:
  name: facebook/bart-large
  path_to_checkpoint: /network/scratch/c/cesare.spinoso/rsasumm/finetuning/2024-08-04-11:46:00.046891/lightning_logs/version_0/checkpoints/epoch=11-step=756.ckpt
generation:
  batch_size: 5
  summary_type: e2e
  generate_kwargs:
    num_return_sequences: 10
    num_beams: 5
    early_stopping: true
    output_scores: true
    return_dict_in_generate: true
output_directory: /network/scratch/c/cesare.spinoso/rsasumm/generate_summaries/bart_finetuned_qfs
write_config_directory: /home/mila/c/cesare.spinoso/RSASumm/src/generate_summaries/config_instances/bart_finetuned_qfs
commit: false
finished_running: false
