dataset_name: multioped
qa_name: llama3_qa
tokenizer:
  name: meta-llama/Meta-Llama-3-8B-Instruct
model:
  name: meta-llama/Meta-Llama-3-8B-Instruct
rescoring:
  type: answer_reconstruction
  preprocessed_dataset_path: /home/mila/c/cesare.spinoso/RSASumm/data/multioped/test.csv
  generated_answers_path: /home/mila/c/cesare.spinoso/RSASumm/data/qa_generation/2024-07-24-11:52:25.428224.jsonl
  generated_summaries_yaml: /home/mila/c/cesare.spinoso/RSASumm/src/generate_summaries/generated_summaries/qfs_summaries.yaml
  batch_size: 8
  prompt: '<|start_header_id|>system<|end_header_id|>You are a helpful, respectful
    and honest assistant specializing in question answering.<|eot_id|><|start_header_id|>user<|end_header_id|>
    Read the following document and then answer the question about it. Your answer
    should be clear, concise and accurate. Do not provide anything else other than
    the answer to the question. Document: {d} Question: {q} Answer: <|eot_id|><|start_header_id|>assistant<|end_header_id|>'
output_directory: /network/scratch/c/cesare.spinoso/rsasumm/rescoring/answer_reconstruction
write_config_directory: /home/mila/c/cesare.spinoso/RSASumm/src/rescoring/config_instances/answer_reconstruction/llama3_qfs
summarizer_name: bart_finetuned_qfs_nucleus_0.95_temp_1.2
finished_running: true
