dataset:
  name: covidet
  path: /home/mila/c/cesare.spinoso/RSASumm/data/covidet/test.csv
  source_name: document
  question_name: question
  reference_name: summary
  document_id_name: document_id
  question_template: Describe the {emotion} of this post.
tokenizer:
  name: meta-llama/Llama-2-7b-chat-hf
  maximum_length: 4096
model:
  name: meta-llama/Llama-2-7b-chat-hf
generation:
  batch_size: 4
  summary_type: e2e
  seed: 42
  generate_kwargs:
    num_beams: 5
    num_return_sequences: 5
    num_beam_groups: 5
    diversity_penalty: 1.0
    do_sample: false
    max_new_tokens: 300
    early_stopping: true
    output_scores: true
    return_dict_in_generate: true
output_directory: /network/scratch/c/cesare.spinoso/rsasumm/generate_summaries/llama2_e2e
write_config_directory: /home/mila/c/cesare.spinoso/RSASumm/src/generate_summaries/config_instances/llama2_e2e
finished_running: false
